#pragma once

namespace app
{
enum class ButtonType
{
    NO_BUTTON,
    SNAPSHOT_BUTTON,
    SAVE_BUTTON,
    DELETE_BUTTON,
    LIVE_CAMERA_BUTTON,
    SELECT_BUTTON,
    DRAW_TEXT_BUTTON,
    DRAW_LETTERS_BUTTON,
    DRAW_ARROW_BUTTON,
    DRAW_CIRCLE_BUTTON,
    DRAW_LINE_BUTTON,
    DRAW_MULTILINE_BUTTON,
    DRAW_RECTANGLE_BUTTON,
    DRAW_SKIN_TEMPLATE_BUTTON,
    ZOOM_IN_BUTTON,
    ZOOM_OUT_BUTTON
};

} // namespace app
