#pragma once

namespace app
{
enum class ButtonType
{
  SCREENSHOT_BUTTON,
  SAVE_BUTTON,
  DELETE_BUTTON,
  UNDO_BUTTON,
  CANCEL_BUTTON,
  DRAW_TEXT_BUTTON,
  DRAW_LETTERS_BUTTON,
  DRAW_ARROW_BUTTON,
  DRAW_CIRCLE_BUTTON,
  DRAW_LINE_BUTTON,
  DRAW_MULTILINE_BUTTON,
  DRAW_RECTANGLE_BUTTON,
  DRAW_SKIN_TEMPLATE_BUTTON
};
  
} // namespace app

